version: '3.2'

services:


  frontend:
    build: frontend
    ports:
      - "20080:80"
      - "20443:443"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    networks:
      - basic-yii-network

  backend:
    build: backend
    ports:
      - "21080:80"
      - "8085:8085"
      - "21443:443"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development frontend-test backend-test sudo gedit /etc/hosts
      - ./:/app
    networks:
      - basic-yii-network

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - basic-yii-network

networks:
  basic-yii-network:
    external: true

